# Generated by Django 5.2.5 on 2025-08-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiocontent",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="videocontent",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="pagecontent",
            index=models.Index(
                fields=["page", "position", "id"], name="pages_pagec_page_id_2513d8_idx"
            ),
        ),
    ]
